//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusBoard.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatusBoard.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.2.3 | (c) jQuery Foundation | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=a.document,e=c.slice,f=c.concat,g=c.push,h=c.indexOf,i={},j=i.toString,k=i.hasOwnProperty,l={},m=&quot;2.2.3&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[\s\uFEFF\xA0]+|[\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_2_3_min {
            get {
                return ResourceManager.GetString("jquery_2_2_3_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#status-board-checks-placeholder .status-OK {
        ///    background-color: lawngreen;
        ///}
        ///
        ///#status-board-checks-placeholder .status-WARNING {
        ///    background-color: orange;
        ///}
        ///
        ///#status-board-checks-placeholder .status-ERROR {
        ///    background-color: tomato;
        ///}
        ///
        ///#status-board-checks-placeholder .status-loading {
        ///    background-color: lightblue;
        ///}
        ///
        ///#status-board-checks-placeholder {
        ///    font-family: monospace;
        ///    font-size: xx-large;
        ///}
        ///.
        /// </summary>
        internal static string StatusBoard_css {
            get {
                return ResourceManager.GetString("StatusBoard_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    &quot;use strict&quot;;
        ///
        ///    var addCheck = function (check) {
        ///        var resultElement = $(
        ///            &quot;&lt;tr class=&apos;status-loading&apos;&gt;&quot; +
        ///            &quot;&lt;td class=&apos;check-result&apos;&gt;...&lt;/td&gt;&quot; +
        ///            &quot;&lt;td class=&apos;check-name&apos;&gt;&quot; + check.Name + &quot;&lt;/td&gt;&quot; +
        ///            &quot;&lt;td class=&apos;check-message&apos;&gt;&lt;/td&gt;&quot; +
        ///            &quot;&lt;/tr&gt;&quot;);
        ///        $.ajax(
        ///        {
        ///            type: &quot;POST&quot;,
        ///            async: true,
        ///            url: &quot;Status/Check/&quot; + check.CheckId,
        ///            data: &quot;{&apos;id&apos;: &apos;&quot; + resultEle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusBoard_js {
            get {
                return ResourceManager.GetString("StatusBoard_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;script src=&quot;status/jQuery&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;status/js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;link href=&quot;status/css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Status board&lt;/h1&gt;
        ///    &lt;div id=&quot;status-board-checks-placeholder&quot;&gt;
        ///        &lt;table&gt;
        ///            &lt;thead&gt;
        ///                &lt;tr&gt;
        ///                    &lt;th&gt;Result&lt;/th&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusPage_html {
            get {
                return ResourceManager.GetString("StatusPage_html", resourceCulture);
            }
        }
    }
}
